 const projects = [
    {
        id: 1,
        name: 'Yoga Track',
        className: 'yoga-track',
        description: ` A Full-Stack mobile first responsive web application for yoga teachers and enthusiasts helping a user to explore and learn avariety of poses, providing an english and sanskrit name for each pose with alphabetic sort based on either. The user can then create an account where he/she can save poses into yoga-flows as inspirations for a class or record of personal practice with notes and personal rating system.`,
        images: ['https://images-for-portfolio.s3.us-east-2.amazonaws.com/yoga-cap-screens/home.png', 'https://images-for-portfolio.s3.us-east-2.amazonaws.com/yoga-cap-screens/login.png', 'https://images-for-portfolio.s3.us-east-2.amazonaws.com/yoga-cap-screens/poses.png', 'https://images-for-portfolio.s3.us-east-2.amazonaws.com/yoga-cap-screens/pick-flow.png', 'https://images-for-portfolio.s3.us-east-2.amazonaws.com/yoga-cap-screens/flow-view.png', 'https://images-for-portfolio.s3.us-east-2.amazonaws.com/yoga-cap-screens/flow-card.png', 'https://images-for-portfolio.s3.us-east-2.amazonaws.com/yoga-cap-screens/card-attr.png'],
        projectLink: 'https://yoga-capstone-fzi2p9v6x.now.sh/landing',
        githubLinkClient: 'https://github.com/KasiaMirowska/yoga-app',
        githubLinkServer: 'https://github.com/KasiaMirowska/yoga-api',
        techList: ['JavaScript, ', 'Node, ', 'React, ', 'React-Context, ', 'Express, ', 'Postgres, ', 'SQL, ', 'HTML5, ', 'CSS3, ', 'JWT Authentication, ', 'Jest, ', 'Mocha, ', 'Chai, ', 'Enzyme, ', 'Zeit, ', 'Heroku, ', 'AWS'],
    },
    {
        id: 2,
        name: 'Noteful',
        className:'noteful',
        description: `A Full-Stack mobile first responsive web application designed to keep track of to-do lists and memos `,
        images: ['https://images-for-portfolio.s3.us-east-2.amazonaws.com/noteful-screens/home.png', 'https://images-for-portfolio.s3.us-east-2.amazonaws.com/noteful-screens/note.png', 'https://images-for-portfolio.s3.us-east-2.amazonaws.com/noteful-screens/new-note.png', 'https://images-for-portfolio.s3.us-east-2.amazonaws.com/noteful-screens/new-folder.png'],
        projectLink: 'https://noteful-app-client-bms8il0pd.now.sh/',
        githubLinkClient: 'https://github.com/KasiaMirowska/Noteful-Context-refactored',
        githubLinkServer: 'https://github.com/KasiaMirowska/notefulSERVER',
        techList:['JavaScript, ', 'Node, ', 'React, ', 'React-Context, ', 'Express, ', 'Postgres, ', 'SQL, ', 'HTML5, ', 'CSS3, ', 'Jest, ', 'Mocha, ', 'Chai, ', 'Enzyme, ', 'Zeit, ', 'Heroku '], 
    },
    {
        id: 3,
        name: 'Bookmarks-app',
        className:'bookmarks',
        description: `A simple application created for saving internet bookmarks`,
        images: ['https://images-for-portfolio.s3.us-east-2.amazonaws.com/other+screens/bookmarks.png', 'https://images-for-portfolio.s3.us-east-2.amazonaws.com/other+screens/new-bookmark.png'],
        projectLink: 'https://kasiamirowska.github.io/bookmarkProject-KasiaMirowska/',
        githubLinkClient: 'https://github.com/KasiaMirowska/bookmarkProject-KasiaMirowska',
        githubLinkServer: '',
        techList: ['JavaScript, ', 'jQuery, ', 'HTML5, ', 'CSS3, ', 'GithubPages, '],  
    },
    {
        id: 4,
        name: 'Waitstaff Calculator',
        className:'calculator',
        description: `An early project calculating tips and taxes for waitstaff`,
        images: ['https://images-for-portfolio.s3.us-east-2.amazonaws.com/other+screens/Screen+Shot+2020-01-26+at+12.43.50+PM.png', 'https://images-for-portfolio.s3.us-east-2.amazonaws.com/other+screens/Screen+Shot+2020-01-26+at+12.44.03+PM.png'],
        projectLink: ' https://kasiamirowska.github.io/waitstaff-calculator/.',
        githubLinkClient: 'https://github.com/KasiaMirowska/waitstaff-calculator',
        githubLinkServer: '',
        techList: ['JavaScript, ', 'jQuery, ', 'HTML5, ', 'CSS3, ', 'GithubPages, '], 
    }
]
export default projects;